Troubleshooting GitHub actions workflow script

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,13 +23,15 @@ jobs:
           # the test-ci NPM script reads the value of the REPORT_FILE environment variable
           npm run test-ci
           # collect the errors from the test report
-          test_errors=$(cat "${REPORT_FILE}" | jq '.tests[] | select(.err.message) | { error: .err.name, title: .fullTitle, message: .err.message }')
-          # expose the collected errors as a step output
-          echo "->${test_errors}<-"
-          error_count=$(echo "${test_errors}" | jq 'length')
-          echo "Found ${error_count} errors"
-          echo "::set-output name=errors::${test_errors}\n"
-          exit "${error_count}"
+          if [ $? -ne 0 ]
+          then
+            test_errors=$(cat "${REPORT_FILE}" | jq '.tests[] | select(.err.message) | { error: .err.name, title: .fullTitle, message: .err.message }')
+            error_count=$(echo "${test_errors}" | jq 'length')
+            echo "Found ${error_count} errors"
+            # expose the collected errors as a step output
+            echo "::set-output name=errors::${test_errors}\n"
+            exit "${error_count}"
+          fi
         env:
           REPORT_FILE: test_report.json
       - name: Notify on error
